config/routes.rb
Rails.application.routes.draw do
  resources :friendships
  resources :posts
  devise_for :users
  get 'home/index'
  get 'home/comunidad'
  get 'home/perfil'
  root to: "home#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/friendship.rb
class Friendship < ApplicationRecord
  belongs_to :user
  belongs_to :friend, class_name: "User"

  validates_uniqueness_of :friend, scope: :user
  validate :check_user
  def check_user
    if self.friend_id == self.user_id
      errors.add(:friend, "can't be yourself")
    end
  end

end

app/models/post.rb
class Post < ApplicationRecord
  mount_uploader :attachment, AvatarUploader
  belongs_to :user
  validates :content, presence: true
  extend FriendlyId
  friendly_id :id

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :posts
  has_many :friendships
  has_many :friends, through: :friendships
  has_many :inverse_friendships, class_name: "Friendship", foreign_key: :friend_id
  has_many :inverse_friends, through:  :inverse_friendships, source: :user
  mount_uploader :profile, AvatarUploader


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  layout :layout_by_resource

  protected

  def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :last_name, :profile,:email, :password) }
      devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:name, :last_name, :profile, :email, :password, :current_password) }
  end

  private

  def layout_by_resource
    if devise_controller?
      "devise"
    else
      "application"
    end
  end

end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController
  before_action :set_friendship, only: [:show, :edit, :update, :destroy]

  def index
    @friendships = Friendship.all
  end

  def show
  end

  def new
    @friendship = Friendship.new
  end

  def edit
  end

  def create
    @friendship = current_user.friendships.build(friend_id: params[:friend_id])
    if @friendship.save
      flash[:notice] = "Added friend."
      redirect_to home_comunidad_path
    else
      flash[:error] = "Unable to add friend."
      redirect_to home_comunidad_path
    end
  end

  def update
    respond_to do |format|
      if @friendship.update(friendship_params)
        format.html { redirect_to home_perfil_path, notice: 'Friendship was successfully updated.' }
        format.json { render :show, status: :ok, location: @friendship }
      else
        format.html { render :edit }
        format.json { render json: @friendship.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @friendship = current_user.friendships.find(params[:id])

    @friendship.destroy
    respond_to do |format|
      format.html { redirect_to home_perfil_path, notice: 'Friendship was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_friendship
      @friendship = Friendship.find(params[:id])
    end

    def friendship_params
      params.require(:friendship).permit(:user_id, :friend_id)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!
  def index
    @post = Post.new
    @diarios = Post.find_by_sql("select posts.* from posts order by created_at DESC ")
  end

  def comunidad
    @users = User.all
  end


  def perfil
    @user = User.find(current_user.id)
    @posts = Post.find_by_sql("select posts.* from posts where posts.user_id=#{current_user.id} order by created_at DESC ")


  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.where(user_id: current_user.id)
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @post = Post.friendly.find(params[:id])
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params) do |post|
      post.user= current_user
    end

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_post
      @post = Post.friendly.find(params[:id])
    end
    def post_params
      params.require(:post).permit(:attachment, :content, :user_id, :public)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/friendships_helper.rb
module FriendshipsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/friendships/_form.html.erb
<%= simple_form_for(@friendship) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.association :user %>
    <%= f.input :friend_id %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/friendships/edit.html.erb
<h1>Editing Friendship</h1>

<%= render 'form', friendship: @friendship %>

<%= link_to 'Show', @friendship %> |
<%= link_to 'Back', friendships_path %>

app/views/friendships/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Friendships</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Friend</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @friendships.each do |friendship| %>
      <tr>
        <td><%= friendship.user %></td>
        <td><%= friendship.friend_id %></td>
        <td><%= link_to 'Show', friendship %></td>
        <td><%= link_to 'Edit', edit_friendship_path(friendship) %></td>
        <td><%= link_to 'Destroy', friendship, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Friendship', new_friendship_path %>

app/views/friendships/new.html.erb
<h1>New Friendship</h1>

<%= render 'form', friendship: @friendship %>

<%= link_to 'Back', friendships_path %>

app/views/friendships/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @friendship.user %>
</p>

<p>
  <strong>Friend:</strong>
  <%= @friendship.friend_id %>
</p>

<%= link_to 'Edit', edit_friendship_path(@friendship) %> |
<%= link_to 'Back', friendships_path %>

app/views/home/comunidad.html.erb
<div class="card-stats">
<div class="row mt-1">
    <% for user in @users %>
    <% if (Friendship.where(user_id: current_user.id, friend_id: user.id).count==0)&& (user.id!=current_user.id) %>

    <div class="col s12 m6 l3">
        <div class="card small gradient-45deg-light-blue-cyan gradient-shadow white-text">
          <div class="card-content">
            <p class=""> <%= user.name  %> <%= user.last_name %>
              <br><%= user.email %>
              <span class="divider"></span>
               Registrado: <%= user.created_at.strftime("%d/%m/%Y") %>
              <hr>
               Ultima vez: <%= user.last_sign_in_at.strftime("%d/%m/%Y a las %I:%M%p" )%>
            </p>
          </div>
            <div class="card-action">
              <%= link_to "Agregar", friendships_path(:friend_id => user), :method => :post , class: "waves-effects waves-light btn"%>
            </div>
        </div>
      </div>
      <%end %>

    <% end %>
</div>
</div>


    </div>
  </div>

app/views/home/index.html.erb
<div class="container">
    <div class="row  ">
        <div class="col s12 m12 l12">
          <div class="card">
            <div class="card-content">
                <%= render "posts/form",  :post => @post %>
            </div>
          </div>
      </div>
      </div>
</div>
<div class="container">
    <% @diarios.each_with_index do |p,index| %>
      <% if !index.odd? %>
        <div class="row">
      <% end %>
      <div class="col s6 m6 l6">
          <div class="card large">
            <div class="card-image">
              <%= image_tag(p.attachment_url) if p.attachment? %>
            </div>
            <div class="card-content">
            <p class="flow-text"><%= p.content %> </p>
              <div class="clear" ></div>
            <p class="small">
                <%= p.user.email %>
                (<%= p.created_at.strftime("%d/%m/%y")%>)
            </p>
            </div>
            <div class="card-action">
                <% if current_user.id==p.user.id %>
                  <%= link_to 'Editar', edit_post_path(p), class:"waves-effect waves-light btn" %>
                <%end %>
                <%= link_to  "ir al post", post_path(p), class:"waves-effect waves-light btn" %>
            </div>
          </div>
      </div>
        <% if index.odd? %>
          </div>
        <% end %>



    <% end %>

</div>

app/views/home/perfil.html.erb
<div id="profile-card" class="card" style="overflow: hidden;">
    <div class="card-image waves-effect waves-block waves-light">
      <%= image_tag "/images/3.png"%>
      <img class="activator" src="images/3.png" alt="user bg">
    </div>
    <div class="card-content">
        <%= image_tag(current_user.profile_url(:thumb), class: "circle responsive-img activator card-profile-image cyan lighten-1 ") if current_user.profile? %>
      <span class="card-title activator grey-text text-darken-4"><%= current_user.name.capitalize%> <%= current_user.last_name.capitalize %></span>
      <p>
        <%= current_user.email%>
      </p>

    </div>

  </div>

  <ul id="projects-collection" class="collection z-depth-1">
      <li class="collection-item">
        <h6 class="flow-text">Post Realizados</h6>
        <p><%= @posts.count %></p>
      </li>
      <% for post in @posts %>
      <li class="collection-item">
        <div class="row">
          <div class="col s9">
            <p class="flow-text">Contenido: <%= post.content %></p>
            <p class="collections-content">Fecha: <%= post.created_at.strftime("%d/%m/%Y")%></p>
          </div>
          <div class="col s3">
            <span class=""><%= link_to "Ver mas", post_path(post), class: "waves-effects waves-light btn " %></span>
          </div>
        </div>
      </li>
      <% end %>


    </ul>

<div class="row 2">
  <% @user.friendships.each_with_index do |friendship,index| %>
    <div class="col s4 m4 l4">
      <div class="card small gradient-45deg-light-blue-cyan gradient-shadow white-text">
        <div class="card-content">
          <p class=""><%= friendship.friend.email %></p>
            <% if @user.inverse_friends.ids.include? friendship.friend_id  %>
              te tiene en su lista de amigos
            <% else %>
            <i class="fa fa-ban">  </i><span style="text-decoration: line-through;"> no te tiene en su lista</span>
            <% end %>
        </div>
        <div class="card-action">
          <%= link_to "destruir amistad", friendship, :method => :delete , class: "waves-effect waves-light btn gradient-45deg-red-pink"%>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/layouts/_content.html.erb
      <!--breadcrumbs end-->
      <!--start container-->
      <div class="container">
        <div class="section">

            <%= yield %>

        </div>
      </div>



    <!-- END CONTENT -->
    <!-- //////////////////////////////////////////////////////////////////////////// -->
    <!-- START RIGHT SIDEBAR NAV-->

    <!-- END RIGHT SIDEBAR NAV-->
  </div>
  <!-- END WRAPPER -->
</div>
<!-- END MAIN -->
<!-- //////////////////////////////////////////////////////////////////////////// -->
<!-- START FOOTER -->
<!-- END FOOTER -->

app/views/layouts/_footer.html.erb
<footer class="page-footer gradient-45deg-light-blue-cyan">
  <div class="footer-copyright">
    <div class="container">
      <span>Copyright ©
      <a class="grey-text text-lighten-2" href="http://nipse.online" target="_blank">xappify</a> All rights reserved.</span>
      <span class="right hide-on-small-only"> Design and Developed by <a class="grey-text text-lighten-2" href="https://thecoderun.com.ve">thecoderun</a></span>
    </div>
  </div>
</footer>

app/views/layouts/_loader.html.erb
<div id="loader-wrapper">
  <div id="loader"></div>
  <div class="loader-section section-left"></div>
  <div class="loader-section section-right"></div>
</div>

app/views/layouts/_sidebar.html.erb
<aside id="left-sidebar-nav ">
  <ul id="slide-out" class="side-nav fixed leftside-navigation">
    <li class="user-details cyan darken-2">
      <div class="row">
        <div class="col col s4 m4 l4">
            <%= image_tag(current_user.profile_url, class: "circle responsive-img valign profile-image cyan") if current_user.profile? %>


        </div>
        <div class="col col s8 m8 l8">
          <ul id="profile-dropdown-nav" class="dropdown-content">
             <li>
                <%= link_to "perfil", home_perfil_path %>
            </li>
          </ul>
          <a class="btn-flat dropdown-button waves-effect waves-light white-text profile-btn" href="#" data-activates="profile-dropdown-nav"><%= current_user.name%> <%= current_user.last_name%>
            <i class="mdi-navigation-arrow-drop-down right"></i></a>
          <p class="user-roal">Operador</p>
        </div>
      </div>
    </li>
    <li class="no-padding">
      <ul class="collapsible" data-collapsible="accordion">
        <li class="bold">
           <%= link_to  root_path , class: "waves-effect waves-cyan" do  %>
              <i class="fa fa-tachometer" aria-hidden="true"></i>
              <span class="nav-text">Dashboard</span>

            <%end %>
        </li>
        <li class="bold">
          <%= link_to posts_path, class: "waves-effect waves-cyan" do %>
            <i class="fa fa-home" aria-hidden="true"></i>
            <span class="nav-text">Posts</span>
          <% end %>

        </li>
        <li class="bold">
          <%= link_to home_comunidad_path, class:"waves-effect waves-cyan" do  %>
              <i class="fa fa-at" aria-hidden="true"></i>
              <span class="nav-text">Comunidad</span>
          <%end%>
        </li>
      </ul>
    </li>
  </ul>
  <a href="#" data-activates="slide-out" class="sidebar-collapse btn-floating btn-medium waves-effect waves-light hide-on-large-only">
    <i class="material-icons">menu</i>
  </a>
</aside>

app/views/layouts/_top.html.erb
<!-- End Page Loading -->
<!-- //////////////////////////////////////////////////////////////////////////// -->
<!-- START HEADER -->
<header id="header" class="page-topbar">
  <!-- start header nav-->
  <div class="navbar-fixed">
    <nav class="navbar-color gradient-45deg-light-blue-cyan">
      <div class="nav-wrapper">
        <ul class="left">
          <li>
            <h1 class="logo-wrapper">
              <%= link_to root_path, class: "brand-logo darken-1" do %>
                <%=  image_tag "logo/materialize-logo.png", alt: "materialize logo" %>
                <span class="logo-text hide-on-med-and-down">Xappify  <sub><font size= "2">0.1.0</font></sub></span>
              <% end %>
            </h1>
          </li>
        </ul>
        <div class="header-search-wrapper hide-on-med-and-down">
          <i class="fa fa-search">

          </i>
          <input type="text" name="Search" class="header-search-input z-depth-2" placeholder="<%= current_user.id %>" />
        </div>
        <ul class="right hide-on-med-and-down">

          <li>
            <a href="javascript:void(0);" class="waves-effect waves-block waves-light notification-button" data-activates="notifications-dropdown">
              <i class="fa fa-globe fa-2x" aria-hidden="true"></i>
            </a>
          </li>
          <li>
            <a href="javascript:void(0);" class="waves-effect waves-block waves-light notification-button" data-activates="notifications-dropdown">
              <i class="fa fa-user fa-2x" aria-hidden="true"></i>
            </a>
          </li>

          <li>
            <a href="javascript:void(0);" class="waves-effect waves-block waves-light profile-button" data-activates="profile-dropdown">
              <span class="avatar-status avatar-online">
                <%= image_tag "avatar/avatar-7.png"%>
                <i></i>
              </span>
            </a>
          </li>

          </li>
        </ul>
        <!-- notifications-dropdown -->
        <ul id="notifications-dropdown" class="dropdown-content">
          <li>
            <h6>NOTIFICATIONS
              <span class="new badge">5</span>
            </h6>
          </li>
          <li class="divider"></li>
          <li>
            <a href="#!" class="grey-text text-darken-2">
              <span class="material-icons icon-bg-circle cyan small">add_shopping_cart</span> A new order has been placed!</a>
            <time class="media-meta" datetime="2015-06-12T20:50:48+08:00">2 hours ago</time>
          </li>
        </ul>
        <!-- profile-dropdown -->
        <ul id="profile-dropdown" class="dropdown-content">
          <% if user_signed_in? %>
          <li>
              <%= link_to('Configuracion', edit_user_registration_path) %>
              </li>
          <li>
            <%= link_to('Logout', destroy_user_session_path, method: :delete) %>
          </li>
          <% else %>
          <li>
            <%= link_to('Login', new_user_session_path)  %>
          </li>
          <% end %>
        </ul>
      </div>
    </nav>
  </div>
  <!-- end header nav-->
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Socialxapia</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application' %>
    <%= javascript_include_tag 'application'%>
  </head>

  <body>
    <%= render "layouts/top"%>
    <div id="main">
        <div class="wrapper">
            <%= render "layouts/sidebar"%>
            <section id="content">
              <%= render "layouts/content"%>
            </section>
          <%= render "layouts/footer" %>

        </div>
      </div>

</body>
</html>

app/views/layouts/devise.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Socialxapia</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application' %>
    <%= javascript_include_tag 'application'%>
  </head>

  <body background="/images/bg.jpg">
    <div id="main">
      <%= yield %>
    </div>
</body>
</html>

app/views/posts/1_form.html.erb
<%= form_with(model: post, local: true) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>
      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :attachment %>
    <%= form.text_field :attachment %>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content  %>
  </div>

  <div class="field">
    <%= form.label :publico %>
    <%= form.select :public, [["si",1],["no",0]],blank: 'Pick someone'%>
  </div>

  <%= form.hidden_field :user_id, id: :post_user_id %>
  <br>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/_form.html.erb
<p id="notice"><%= notice %></p>

<div class="row">
    <div class="col s12">
        <div class="card-panel">





<%= simple_form_for @post  do |form| %>
<%= form.hidden_field :user_id%>

<div class="row">
  <div class="col s12 m12 l12">
    <div class="materialize-textarea">
      <%= form.input :content , as: :text,required: true , label: false, placeholder: "Cuentanos algo bonito este dia !!!",input_html: { class: 'materialize-textarea' }%>
    </div>
  </div>
  </div>
  <div class="row">
  <div class="col s3 m3 l3">
      <%= form.input :public, as: :boolean, checked_value: true, unchecked_value: false, input_html: { class: 'filled-in'}, label: " publico?"%>
      <%= image_tag(@post.attachment_url(:normal)) if @post.attachment? %>

      <%= form.input :attachment, label: false  %>

  </div>
</div>

<div class="card-action">
  <div row>
    <div class="right col s2 m2 l2">
      <div class="actions">
      <%= form.submit  class:"btn waves-effect waves-light "%>
    </div>
    </div>
  </div>
</div>
<% end %>

</div>
</div>

</div>

app/views/posts/edit.html.erb
<%if current_user.id== @post.user.id %>

<%= render 'form', post: @post %>

<%= link_to 'Mostrar', @post %> |
<%= link_to 'Volver', posts_path %>
<%else %>
<script type="text/javascript">
  window.location.href="/"  // put your correct path in a string here
</script>
<%end%>

app/views/posts/index.html.erb
<div class="container">
    <% @posts.each_with_index do |p,index| %>
      <% if !index.odd? %>
        <div class="row">
      <% end %>
      <div class="col s6 m6 l6">
          <div class="card large">
            <div class="card-image">
              <%= image_tag(p.attachment_url) if p.attachment? %>
            </div>
            <div class="card-content">
            <p class="flow-text"><%= p.content %> </p>
              <div class="clear" ></div>
            <p class="small">
                <%= p.user.email %>
                (<%= p.created_at.strftime("%d/%m/%y")%>)
            </p>
            </div>
            <div class="card-action">
                <% if current_user.id==p.user.id %>
                  <%= link_to 'Editar', edit_post_path(p), class:"waves-effect waves-light btn" %>
                <%end %>
                <%= link_to  "ir al post", post_path(p), class:"waves-effect waves-light btn" %>
            </div>
          </div>
      </div>
        <% if index.odd? %>
          </div>
        <% end %>



    <% end %>

</div>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<div class="row">
    <div class="col s12">
        <div class="card-panel">
            <%= image_tag(@post.attachment_url(:normal)) if @post.attachment? %>
          <p class="flow-text">
            <%= @post.content %>
          </p>
          <p>
          <% if @post.public %>
            Post publico
          <% else %>
            Post privado
          <% end %>
        </p>
        </div>
      </div>

</div>
<% if current_user.id==@post.user.id %>
  <%= link_to 'Editar', edit_post_path(@post) %> |
<%end %>

<%= link_to 'Volver', home_index_path %>